Legacy
actimeller/junior-course-boilerplate pull request #10
Opened 2020-02-02 12:23 UTC by actimeller

2020-02-03 16:12 UTC, vislogurov requested changes

2020-02-03 16:12 UTC, vislogurov commented on src/containers/BasketListContainer.js
> +                    this.props.loadProductsFail(response.message);
А есть ли смысл в этой ветке? Любое падение на этапе response.ok, вызовет reject промиса и он провалится в catch, где уже вызывается loadProductsFail

2020-02-03 19:53 UTC, actimeller commented on src/containers/BasketListContainer.js
> +                    this.props.loadProductsFail(response.message);
Да, видимо смысла нет. Исправил

2020-02-06 07:48 UTC, vislogurov approved these changes

2020-02-06 08:02 UTC, merged